### PR TITLE
Implement basic fly camera

### LINKED ISSUE #18: Create basic fly camera
The general idea is to have a first-person fly camera with something like debug lines to make orientation easy. I would like this to be something Minecraft-esque as far as controls and behavior goes.

Amethyst's [`FreeRotationSystem`](https://docs.amethyst.rs/stable/amethyst_controls/struct.FreeRotationSystem.html) doesn't clamp the camera movement at all, allowing front-flip-like motion, and [`FlyMovementSystem`]() uses [`Transform::append_translation_along()`](https://docs.amethyst.rs/stable/amethyst_core/transform/components/struct.Transform.html#method.append_translation_along) internally, so [`FlyControlBundle`](https://docs.amethyst.rs/stable/amethyst_controls/struct.FlyControlBundle.html) is a no-go. My proposal is that we create a custom implementation of each of the `System`s from `FlyControlBundle` (potentially in a `SystemBundle` if I learn how to make them) to tailor them to the Minecraft-esque requirement.

### PR DESCRIPTION
**Pull request by lberrymage**
Resolves #18

### CODE REVIEW

**Comment by lberrymage** [comment]
@aayux, I know it's been a while, but do you want to review this? Just thought I'd throw it out there since you seemed interested in contributing. The main things I'm concerned about are the following:

- Camera "flipping"

- Movement feeling wonky, changing direction when crossing axes, etc.

As far as I can tell these seem to be fixed, but I want to see if others have any problems. Of course if you see anything else to poke at, by all means do so. Maybe my code looks ugly.

Naturally anyone else who sees this is welcome to test and review as well.

**Comment by aayux** [comment]
I can definitely take a look, happy to help!

**Comment by lberrymage** [comment]
Thanks for pointing that out - I'll definitely fix it. Don't exactly want someone's first impression to be "this looks broken."

Good to hear that the camera feels okay too. And I should have been more clear on what I meant by "flipping"; what I meant is being able to rotate the camera upward or downward more than 90 degrees so that the camera can essentially do a frontflip/backflip. At one point it would happen occasionally, and I just wanted to check that my fix truly worked. I've had a friend test it and it looks like it's working properly now (i.e. the camera won't flip), so don't worry if you didn't mess with that in particular.

Thank you for taking time to review this by the way! I really appreciate it. I'll make the change you suggested and then we should be ready for merging.

**Comment by aayux** [comment]
Ah, I see. No I didn't observe any flipping when I did that either.

**Comment by lberrymage** [comment]
Awesome. Sounds like we're good to go.

bors r=lberrymage,aayux p=5

**Comment by lberrymage** [comment]
bors r=lberrymage r=aayux p=5

**Comment by lberrymage** [comment]
bors r=lberrymage, aayux p=5

**Pull request merged**
